name: "calling workflow - docker build and push for ljc-helper"

on:
  push:
    branches:
      - "*"

env:
  DOCKER_FILE_LOCATION: ./Dockerfile

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_FILE_LOCATION: ${{ env.DOCKER_FILE_LOCATION }}
    steps:
      - run: echo "Exposing env vars"

  build-push-docker:
    needs: vars
    name: "Calling docker build and push"
    uses: ljcheng999/cicd-pipeline/.github/workflows/reuse-docker-build-push.yaml@main
    with:
      DOCKER_FILE_LOCATION: ${{ needs.vars.outputs.DOCKER_FILE_LOCATION }}
    secrets:
      repo-name: ${{ secrets.REPO_NAME }}
    # with:
    #   DOCKER_FILE_LOCATION: ${{ needs.vars.outputs.DOCKER_FILE_LOCATION }}
    #   build-args: |
    #     REPO_NAME=${{ secrets.REPO_NAME }}
    # secrets: inherit
