name: "docker build and push for ljc-helper"

on:
  workflow_dispatch:

  # push:
  #   tags:
  #     - main
  #     - "*"

env:
  DOCKER_FILE_LOCATION: ./Dockerfile

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_FILE_LOCATION: ${{ env.DOCKER_FILE_LOCATION }}
    steps:
      - run: echo "Exposing env vars"

  build-push-docker:
    needs: vars
    name: "Calling docker build and push"
    uses: ljcheng999/cicd-pipeline/.github/workflows/docker-build-push.yaml@main
    with:
      DOCKER_FILE_LOCATION: ${{ needs.vars.outputs.DOCKER_FILE_LOCATION }}
    secrets: inherit
